---
apiVersion: v1
kind: Service
metadata:
  name: billing-postgres
  namespace: {{ .Values.namespace }}
  labels:
    app: billing-postgres
spec:
  type: NodePort
  ports:
   - port: {{ .Values.externalPostgresql.billingservice.postgresqlPort }}
     targetPort: {{ .Values.externalPostgresql.targetPort }}
  selector:
    app: billing-postgres

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: billing-postgres-statefulset
  namespace: {{ .Values.namespace }}
spec:
  serviceName: "billing-postgres"
  replicas: 1
  selector:
    matchLabels:
      app: billing-postgres
  template:
    metadata:
      labels:
        app: billing-postgres
    spec:
      containers:
      - name: billing-postgres
        image: {{ .Values.postgres.image }}
        ports:
        - containerPort: {{ .Values.externalPostgresql.targetPort }}
          name: postgredb
        env:
          - name: POSTGRES_DB
            value: {{ .Values.externalPostgresql.billingservice.postgresqlDatabase }}
          - name: POSTGRES_USER
            value: {{ .Values.externalPostgresql.billingservice.postgresqlUserName }}
          - name: POSTGRES_PASSWORD
            value: {{ .Values.externalPostgresql.billingservice.postgresqlPassword }}
        volumeMounts:
        - name: postgredb
          mountPath: /var/lib/postgresql/data
          subPath: postgres
  volumeClaimTemplates:
  - metadata:
      name: postgredb
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "standard"
      resources:
        requests:
          storage: 2G


