apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "streaming-chart.fullname" . }}
  namespace: {{ .Values.namespace }}
  annotations:
    kubernetes.io/ingress.class: nginx
    # nginx.ingress.kubernetes.io/rewrite-target: /health
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  rules:
    - host: {{ .Values.ingress.hostname }}
      http:
        paths:
          - path: /person
            pathType: Exact
            backend:
              service:
                name: person-service
                port:
                  number: {{ .Values.service.personservice.port }}
          - path: /account
            pathType: Exact
            backend:
              service:
                name: billing-service
                port:
                  number: {{ .Values.service.billingservice.port }}
          - path: /order
            pathType: Exact
            backend:
              service:
                name: order-service
                port:
                  number: {{ .Values.service.orderservice.port }}
          - path: /notice
            pathType: Exact
            backend:
              service:
                name: notification-service
                port:
                  number: {{ .Values.service.notificationservice.port }}
