apiVersion: v1
kind: Service
metadata:
  name: person-service
  namespace: {{ .Values.namespace }}
  labels:
   app: person-service
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.personservice.port }}
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
   app: person-service
---
apiVersion: v1
kind: Service
metadata:
  name: billing-service
  namespace: {{ .Values.namespace }}
  labels:
   app: billing-service
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.billingservice.port }}
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: billing-service
---
apiVersion: v1
kind: Service
metadata:
  name: order-service
  namespace: {{ .Values.namespace }}
  labels:
    app: order-service
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.orderservice.port }}
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: order-service
---
apiVersion: v1
kind: Service
metadata:
  name: notification-service
  namespace: {{ .Values.namespace }}
  labels:
    app: notification-service
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.notificationservice.port }}
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
   app: notification-service

