---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: zookeeper
  name: zookeeper
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zookeeper
  template:
    metadata:
      labels:
        app: zookeeper
    spec:
      containers:
        - image: {{ .Values.images.zookeeper.repository }}
          imagePullPolicy: IfNotPresent
          name: zookeeper
          ports:
            - containerPort: 2181
          env:
            - name: ZOO_MY_ID
              value: "1"
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: zookeeper-service
  name: zookeeper-service
  namespace: {{ .Values.namespace }}
spec:
  type: NodePort
  ports:
    - name: zookeeper-port
      port: {{ .Values.service.zookeeper.port}}
      # nodePort: 30181
      targetPort: 2181
  selector:
    app: zookeeper